cc_test(
    name = "lenet_lite_asymu8_cc",
    copts = [
        "-Werror", "-std=c++14"
    ],
    srcs = [
        "lenet_lite_asymu8.cc",
        "lenet_lite_asymu8_executable.h"
    ],
    deps = [
        "//:tim-lite_interface"
    ],
)
