cc_test(
    name = "lenet_asymu8_cc",
    copts = [
        "-Werror", "-std=c++14"
    ],
    srcs = [
        "lenet_asymu8.cc",
        "lenet_asymu8_weights.h"
    ],
    deps = [
        "//:tim-vx_interface"
    ],
)
